# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Mita/readFile/readFile.cache/wt [current_project]
set_property parent.project_path C:/Users/Mita/readFile/readFile.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib C:/Users/Mita/Documents/VIBOT/RP_test/tb1.vhd
synth_design -top read_file -part xc7z020clg484-1
write_checkpoint -noxdef read_file.dcp
catch { report_utilization -file read_file_utilization_synth.rpt -pb read_file_utilization_synth.pb }
