# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Mita/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/Mita/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/async_fifo.v
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/FifoBuffer.v
}
read_vhdl -library bftLib {
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bftLib/core_transform.vhdl
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bftLib/bft_package.vhdl
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bftLib/round_4.vhdl
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bftLib/round_3.vhdl
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bftLib/round_2.vhdl
  C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bftLib/round_1.vhdl
}
read_vhdl -library xil_defaultlib C:/Users/Mita/project_2/project_2.srcs/sources_1/imports/Sources/bft.vhdl
read_xdc C:/Users/Mita/project_2/project_2.srcs/constrs_1/imports/xc7k70tfbg484-2/bft_full.xdc
set_property used_in_implementation false [get_files C:/Users/Mita/project_2/project_2.srcs/constrs_1/imports/xc7k70tfbg484-2/bft_full.xdc]

synth_design -top bft -part xc7k70tfbg484-2
write_checkpoint -noxdef bft.dcp
catch { report_utilization -file bft_utilization_synth.rpt -pb bft_utilization_synth.pb }
