# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Mita/Documents/VIBOT/Robotic Project/Mita_Playground/ImageProcessing/imageProcessing.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Mita/Documents/VIBOT/Robotic Project/Mita_Playground/ImageProcessing/imageProcessing.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Mita/Documents/VIBOT/Robotic Project/Mita_Playground/imadder.vhd}
  {C:/Users/Mita/Documents/VIBOT/Robotic Project/Mita_Playground/imgadder_test.vhd}
}
synth_design -top imgadder_test -part xc7z020clg484-1
write_checkpoint -noxdef imgadder_test.dcp
catch { report_utilization -file imgadder_test_utilization_synth.rpt -pb imgadder_test_utilization_synth.pb }
